collections:
#  - community.general
   - name: redhat.openshift
     version: 5.0.0 
     source: https://hub-aap.apps.ocp4.example.com/api/galaxy/


   - name: ovirt.ovirt
     version: 3.2.0
     source: https://hub-aap.apps.ocp4.example.com/api/galaxy/
