collections:
#  - community.general
   - name: kubernetes.core
     version: 6.2.0
     source: https://hub-aap.apps.ocp4.example.com/api/galaxy/


#   - name: redhat.openshift
#     version: 5.0.0 
#     source: https://hub-aap.apps.ocp4.example.com/api/galaxy/


   - name: ovirt.ovirt
     version: 3.2.0
     source: https://hub-aap.apps.ocp4.example.com/api/galaxy/
