- hosts: localhost
  module_defaults:
    redhat.openshift.openshift:
      host: https://api.ocp4.example.com:6443/
      validate_certs: false 
     #ca_cert: ca.pem
  tasks:
        - name: Log in (obtain access token)
          redhat.openshift.openshift_auth:
            username: admin
            password: redhatocp
          register: openshift_auth_results

        # Previous task provides the token/api_key, while all other parameters
        # are taken from module_defaults
        - name: Get a list of all pods from any namespace
          kubernetes.core.k8s_info:
            api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
            kind: Pod
          register: pod_list
