- name: Create VMs
  hosts: all
  vars:
    cloud_pass: changeme
    lab_rsa: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGtUW3ismHyuCW4CDdTVOOOq6aySdtYenXFWWx7HJa4VTepkG00aaLId9ocra10hc+MB0GTJMCyabDv3i8NKdi6GDH/aOLVsp/Ewy8DEzZMBlJDCt4v2i4/wU4liw6KgEFkZs+5hnqU8d4QzldyGJ5onr+AGvFOKG68CS0BBl40Z1twf1HhCyx8k6nzD2ovlkxWRFZKPAFrtPCBVvQDkOfVFZF+lwzaSztgAjbFZ4A9jqQyUYx4kOJ5DtRef36ucdUdVQale0+8lICl7/gb142SPpYfhxe88/BJScLPRjvVNeu1TxRmoHtVazqnAoRxQYAn2MoI6AG+w6QuZf8f7aL LabGradingKey"

  tasks:

    - name: Create labkey secret
      redhat.openshift.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: labkey
            namespace: "{{ target_ns }}"
          type: Opaque
          data:
            key: "{{ lab_rsa | b64encode }}"

    - name: Create VM from template
      vars:
        j2vm_name: j2vm
        itype: u1.small
        add_net: true
      redhat.openshift.k8s:
        state: present
        template: "templates/create_vm.yml.j2"
      register: templatevm
      until: templatevm is succeeded
      retries: 60
      delay: 10
      failed_when: templatevm is failed or templatevm.failed

    - name: Include task to create vm
      ansible.builtin.import_tasks: tasks/create_vm_task.yml
      vars:
        vm_settings:
          - vmname: 'small'
            itype: 'u1.small'
          - vmname: 'medium'
            itype: 'u1.medium'
